### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by philsquared** [jtorjo/logwizard#3] opened 2015-12-31 10:03 UTC
Sorry to spoil your pristine issues list - especially with an issue that may be almost completely out your control - but I feel I should try.

I've been trying to install the 64-bit MSI of the 1.6.1 release (the first time I have tried to install logwizard) on my Windows 7 machine.

However, after accepting the default install directory (C:\Program Files\...) and clicking Next I get a dialog telling me that "The amount of required disk space exceeds the amount of available disk space", followed by a breakdown of volumes that contradicts that!

I'll try and embed a capture of that dialog here:

![image](https://cloud.githubusercontent.com/assets/92878/12063352/526e7e48-afa5-11e5-87b1-2e6db9a4f490.png)

(btw scrolling down this list just shows a few more volumes with 0KB required).

This looks like an issue with the installer tool (InstallShield?) - and probably some weird interaction with my environment - I'm sure you would have heard by now if everyone was seeing the same thing! But if you have any ideas or have seen anything similar I'd love to hear as I'm keen to try logwizard out.

**Comment by jtorjo** [comment] 2015-12-31 10:37
Hi Phil,

That's a weird one indeed :) No one else has encountered this.
The installer is a Visual studio installer project. And yes, this has been tried on other Win7 machines.

Can you please take a look of anything out of the ordinary in Windows Event Log?

I suspect there may be something with your installer - anyway, if all fails, could we try a teamviewer?

Best,
John

**Comment by philsquared** [comment] 2015-12-31 10:50
Thanks for getting back.

The only reference in the event log is: "Installation success or error status: 1602" - which I believe just means "user cancels installation" (which I did after failing to get past that dialog).
If by TeamViewer you mean some sort of remote access - that's not going to be possible as this is a work machine - and I work at a bank!

I'll try on another machine here.

**Comment by jtorjo** [comment] 2015-12-31 10:54
I see...
Did you by any chance try to install for "All Users", or from a user that does not have admin credentials, or from Windows 7 Home edition?

I just installed it on a VM7 Pro machine, admin credentials + "Current User", and it works.

Best,
John

**Comment by philsquared** [comment] 2015-12-31 10:58
This is Windows 7 Enterprise (SP1). It's a dev machine with full admin rights (ie my login is in the admin group).
I initially tried the "all users" option (although it didn't get as far as the elevation dialog) but also tried "current user" with the same result. I tried both 64 and 32-bit packages.

**Comment by philsquared** [comment] 2015-12-31 11:06
Just tried it on my second machine (same specs) - with the same result :-(

**Comment by jtorjo** [comment] 2015-12-31 12:25
Can we teamviewer on your second machine?

**Comment by philsquared** [comment] 2015-12-31 13:31
sadly it's the same situation with that one

**Comment by jtorjo** [comment] 2015-12-31 16:36
Weird - please check you email - I've written to you.

**Comment by jtorjo** [comment] 2016-01-05 12:27
Following our private conversation - I think the problem is indeed with setup kit writing into Roaming directory. I will look into it - see if there's another way to do it.

**Comment by jtorjo** [comment] 2016-01-05 13:31
This is a really weird one to fix, since there's so little info out there. I'm 98% sure it's due to the Roaming directory. My question now is : do you have any write rights to the Roaming directory, or there is an upper limit to how much you can write there?

My take (and hopefully that is the case), is that it's the latter. In this case, you should be able to install an older version :  https://github.com/jtorjo/logwizard/releases/tag/1.3.2

If this is indeed the case, I can modify the setup kit to keep things in "Local" directory.

Best,
John

**Comment by philsquared** [comment] 2016-01-08 10:01
Sorry for the delay getting back - been a manic week this week!

Thanks for looking into this - especially as I can't give you much information.
Unfortunately your hunch seems to be wrong. I tried 1.3.2 - same result. I tried a couple of even earlier versions - including 1.0.61 (first public release) - all with the same result :-(

**Comment by jtorjo** [comment] 2016-01-08 11:06
This is very weird.
Note that I just published anew release (1.6.7) which doesn't touch Roaming directory at all.
Can you please give it  a try? Thanks!

**Comment by jtorjo** [comment] 2016-01-29 13:43
As per our offline talk, I'm closing this issue. For some very strange reason, not even the latest version (1.7.3) doesn't actually stop the error. Seems to be related to some restrictions at your work place.

You said you'll look into compiling this on your machine. Please keep me posted ;)

**Closed by jtorjo** 2016-01-29 13:43 UTC
