### ISSUE TITLE
log_view_parent not implemented fully

### ISSUE THREAD

**Issue by reader-man** [jtorjo/logwizard#2] opened 2015-12-26 23:15 UTC
hI,
Thanks on the excellent log viewer, you have made.

but when i downloaded the master.zip, and opened it with VS 2015, it gave the following errors:
Error:CS0535	'test_log_view' does not implement interface member 'log_view_parent.description_columns()'	test_ui	E:\_Flash\LogWizard 1.6.3a\logwizard-master\src\test_ui\test_log_view.cs	15	Active
Error:Could not copy the file "E:\_Flash\LogWizard 1.6.3a\logwizard-master\src\samples\uk_small.sample.log" because it was not found.	LogWizard			
Error:Could not copy the file "E:\_Flash\LogWizard 1.6.3a\logwizard-master\src\samples\LogWizard.sample.log" because it was not found.	LogWizard

plus numerous warnings.

and even when i implemented the interface it did not run because of the second and third errors above.

Regards, and thanks again.

**Comment by jtorjo** [comment] 2015-12-28 07:31
Hi,

Thanks for the kind words :)

1. test_ui error fixed (1.6.3b)
2. warnings fixed (1.6.3b)
3. About the samples - that is a bit more complicated - normally you should simply ignore those errors. The issue is that one of the log files are really big (5Mb), and it chokes github. So I chose to manually ignore those files. I would remove the 'samples' directory from the project, but it's marked as "Content" - when I'm generating the setup kit.

If you have any idea about this please let me know - otherwise, you can simply remove the 'samples' directory from the project, and compile.

Best,
John

**Closed by jtorjo** 2015-12-28 07:31 UTC

**Comment by reader-man** [comment] 2015-12-31 08:44
Thanks, again for your fast response.

(1.6.3b) has fixed all errors and warnings.

Maybe my suggestion is naive, but it will stop this question coming from others.

maybe if you can change the two files content to have only several pages of log data, this will make github accept them.

and make a .bat script, that is called from the build events (post-Build), that will search for these same files in your local HDD, and if found, it will over-write the output folder, and if not found, do nothing.

This will make it work on your computer as you wanted, and work on others computer, because it will not find the files on their computers, so it will not make a problem, but if you do it, test your solution on 2 different computers or VMs.

again, thanks, its a great log viewer.

**Comment by jtorjo** [comment] 2015-12-31 10:47
Thanks for the kind words :)
The idea behind the rather large files was to show off some of the power of LogWizard.

The problem with a .bat script - I think -, is that they would still show up in github after they would be rewritten (as modified), which could then trigger the same github issue.

Another option would be to tell git they are binary files - so it would not try to read it. I see that this may be possible with Git attributes - have to look into it a bit.

**Comment by reader-man** [comment] 2015-12-31 13:17
I know that its for log samples, i hope your idea work.

if it does not, you can always make the log files as links to a shared drive on the net, for others to download it, and mention that in the help me file.

 because while your intention is very nice, but having a compilation error, is a more deterrent than the benefits of having the example files, from the perspective of the other developer, as it gives them the notion that the code does not have good quality, and its developer commits code that was not checked, and last, i think there others will ask you about these errors.

last, i will stop talking about this, so it will not be nagging.

Thanks; from my perspective, this is a very nice code base, and will certainly consider it in my next projects.

farewell, and good luck.

**Comment by jtorjo** [comment] 2015-12-31 16:37
Coolio! You're correct about the compilation error - I should find a way to fix it.

Will give it a shot after New Year's :)

Best,
John

**Comment by reader-man** [comment] 2015-12-31 19:49
Happy new year.

**Comment by jtorjo** [comment] 2016-01-05 12:13
Happy New Year!
(sorry for the late reply :))

**Comment by jtorjo** [comment] 2016-01-05 12:26
Awesooome!!! Adding .gitattributes worked! :D
